# Generated by Django 4.1.2 on 2022-10-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='upload',
            new_name='uploaded',
        ),
    ]
